export { default as NavBar } from './Navbar/Navbar.jsx'
export { default as Button } from './Button/Button.jsx'
export { default as Logo } from './Logo/Logo.jsx'
export { default as Text } from './Text/Text.jsx'
export { default as SocialMedia } from './SocialMedia/SocialMedia.jsx'
export { default as CopyRight } from './CopyRight/Copyright.jsx'
